@echo off
setlocal EnableExtensions EnableDelayedExpansion

cd /d "%~dp0"
set "LOG_FILE=%TEMP%\InstantLoginSwitcher-uninstall.log"

echo ============================================== > "!LOG_FILE!"
echo InstantLoginSwitcher uninstall started %DATE% %TIME% >> "!LOG_FILE!"
echo Working directory: %CD% >> "!LOG_FILE!"

echo InstantLoginSwitcher uninstaller
echo.
echo Log file: !LOG_FILE!
echo.

net session >nul 2>&1
if not "!errorlevel!"=="0" (
    echo This uninstaller must be run as Administrator.
    echo Please right-click this file and choose "Run as administrator".
    echo ERROR: not running as admin >> "!LOG_FILE!"
    echo.
    pause
    exit /b 1
)

set "CORE_SCRIPT=%CD%\scripts\Setup-InstantLoginSwitcher.ps1"
if not exist "!CORE_SCRIPT!" (
    echo Could not find core setup script:
    echo !CORE_SCRIPT!
    echo ERROR: missing core script >> "!LOG_FILE!"
    echo.
    pause
    exit /b 1
)

set "ILS_MODE=Uninstall"
set "PS_BOOTSTRAP=JABFAHIAcgBvAHIAQQBjAHQAaQBvAG4AUAByAGUAZgBlAHIAZQBuAGMAZQAgAD0AIAAnAFMAdABvAHAAJwAKAHQAcgB5ACAAewAKACAAIAAgACAAJABzAGMAcgBpAHAAdABQAGEAdABoACAAPQAgACQAZQBuAHYAOgBDAE8AUgBFAF8AUwBDAFIASQBQAFQACgAgACAAIAAgAGkAZgAgACgAWwBzAHQAcgBpAG4AZwBdADoAOgBJAHMATgB1AGwAbABPAHIAVwBoAGkAdABlAFMAcABhAGMAZQAoACQAcwBjAHIAaQBwAHQAUABhAHQAaAApACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAHQAaAByAG8AdwAgACcAQwBPAFIARQBfAFMAQwBSAEkAUABUACAAZQBuAHYAaQByAG8AbgBtAGUAbgB0ACAAdgBhAHIAaQBhAGIAbABlACAAaQBzACAAbQBpAHMAcwBpAG4AZwAuACcACgAgACAAIAAgAH0ACgAKACAAIAAgACAAaQBmACAAKAAtAG4AbwB0ACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABzAGMAcgBpAHAAdABQAGEAdABoACkAKQAgAHsACgAgACAAIAAgACAAIAAgACAAdABoAHIAbwB3ACAAIgBDAG8AcgBlACAAcwBjAHIAaQBwAHQAIABuAG8AdAAgAGYAbwB1AG4AZAA6ACAAJABzAGMAcgBpAHAAdABQAGEAdABoACIACgAgACAAIAAgAH0ACgAKACAAIAAgACAAJABzAGMAcgBpAHAAdABUAGUAeAB0ACAAPQAgAEcAZQB0AC0AQwBvAG4AdABlAG4AdAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABzAGMAcgBpAHAAdABQAGEAdABoACAALQBSAGEAdwAKACAAIAAgACAAJABjAG8AcgBlACAAPQAgAFsAUwBjAHIAaQBwAHQAQgBsAG8AYwBrAF0AOgA6AEMAcgBlAGEAdABlACgAJABzAGMAcgBpAHAAdABUAGUAeAB0ACkACgAKACAAIAAgACAAJABtAG8AZABlACAAPQAgACQAZQBuAHYAOgBJAEwAUwBfAE0ATwBEAEUACgAgACAAIAAgAGkAZgAgACgAWwBzAHQAcgBpAG4AZwBdADoAOgBJAHMATgB1AGwAbABPAHIAVwBoAGkAdABlAFMAcABhAGMAZQAoACQAbQBvAGQAZQApACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAHQAaAByAG8AdwAgACcASQBMAFMAXwBNAE8ARABFACAAZQBuAHYAaQByAG8AbgBtAGUAbgB0ACAAdgBhAHIAaQBhAGIAbABlACAAaQBzACAAbQBpAHMAcwBpAG4AZwAuACcACgAgACAAIAAgAH0ACgAKACAAIAAgACAAaQBmACAAKAAkAG0AbwBkAGUAIAAtAGUAcQAgACcASQBuAHMAdABhAGwAbAAnACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACYAIAAkAGMAbwByAGUAIAAtAE0AbwBkAGUAIABJAG4AcwB0AGEAbABsACAALQBQAHIAaQBtAGEAcgB5AFUAcwBlAHIAIAAkAGUAbgB2ADoASQBMAFMAXwBQAFIASQBNAEEAUgBZAF8AVQBTAEUAUgAgAC0AUwBlAGMAbwBuAGQAYQByAHkAVQBzAGUAcgAgACQAZQBuAHYAOgBJAEwAUwBfAFMARQBDAE8ATgBEAEEAUgBZAF8AVQBTAEUAUgAKACAAIAAgACAAfQAKACAAIAAgACAAZQBsAHMAZQBpAGYAIAAoACQAbQBvAGQAZQAgAC0AZQBxACAAJwBVAG4AaQBuAHMAdABhAGwAbAAnACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACYAIAAkAGMAbwByAGUAIAAtAE0AbwBkAGUAIABVAG4AaQBuAHMAdABhAGwAbAAKACAAIAAgACAAfQAKACAAIAAgACAAZQBsAHMAZQAgAHsACgAgACAAIAAgACAAIAAgACAAdABoAHIAbwB3ACAAIgBVAG4AcwB1AHAAcABvAHIAdABlAGQAIABtAG8AZABlADoAIAAkAG0AbwBkAGUAIgAKACAAIAAgACAAfQAKAAoAIAAgACAAIABlAHgAaQB0ACAAMAAKAH0ACgBjAGEAdABjAGgAIAB7AAoAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAJABfAC4ARQB4AGMAZQBwAHQAaQBvAG4ALgBNAGUAcwBzAGEAZwBlAAoAIAAgACAAIABpAGYAIAAoAC0AbgBvAHQAIABbAHMAdAByAGkAbgBnAF0AOgA6AEkAcwBOAHUAbABsAE8AcgBXAGgAaQB0AGUAUwBwAGEAYwBlACgAJABlAG4AdgA6AEwATwBHAF8ARgBJAEwARQApACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAEEAZABkAC0AQwBvAG4AdABlAG4AdAAgAC0ATABpAHQAZQByAGEAbABQAGEAdABoACAAJABlAG4AdgA6AEwATwBHAF8ARgBJAEwARQAgAC0AVgBhAGwAdQBlACAAJABfAC4ARQB4AGMAZQBwAHQAaQBvAG4ALgBUAG8AUwB0AHIAaQBuAGcAKAApAAoAIAAgACAAIAB9AAoAIAAgACAAIABlAHgAaQB0ACAAMQAKAH0A"

echo Running in-memory PowerShell core... >> "!LOG_FILE!"

powershell.exe -NoLogo -NoProfile -ExecutionPolicy Bypass -EncodedCommand !PS_BOOTSTRAP! >> "!LOG_FILE!" 2>&1

set "EXIT_CODE=%errorlevel%"
echo PowerShell exit code: !EXIT_CODE! >> "!LOG_FILE!"
echo.

if not "!EXIT_CODE!"=="0" (
    echo Uninstall failed with exit code !EXIT_CODE!.
    echo See log: !LOG_FILE!
    echo.
    pause
    exit /b !EXIT_CODE!
)

echo Uninstall completed.
echo See log: !LOG_FILE!
echo.
pause
exit /b 0
